-- Generated by nwg-displays on 2026-07-14 at 04:26:14. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "3840x2160@60.0",
    position = "0x0",
    scale = 1.5,
    bitdepth = 10
})
